Add better diff output for string comparison.
msackman/argot pull request #5
Opened 2017-07-28 11:42 UTC by Ferada

Will always output colours.  That's a point for improvement and should
likely be configurable and/or determined by the output/terminal
capabilities.  In general the library also supports custom output (e.g.
a HTML one is available).

2017-08-02 13:42 UTC, msackman requested changes
Couple of tiny suggestions. In general fine. Slightly vexing that we're trying to come up with structured in errors in general. Suggests a design wart to me - maybe the 'error' type just isn't the right one. But let's leave that for another day.

2017-08-02 13:42 UTC, msackman commented on http.go
> +			return fmt.Errorf("Header: '%s': Differed: '%s'.", key, diff(value, header))
"Differed" seems an unusual word to me - just "Diff"?

2017-08-02 13:42 UTC, msackman commented on http.go
> +			return fmt.Errorf("Body: Differed: '%s'.", diff(value, got))
Same here. Also, s/got/bodyStr/ ?

2017-08-03 12:21 UTC, Ferada commented
It's not really about errors though, but any kind of potentially less structured output, or where you want to see the exact difference before parsing, especially since the `encoding/*` libraries are so lenient on parsing. I'll update rest.

2017-08-04 10:35 UTC, msackman approved these changes

2017-08-04 10:35 UTC, merged